apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-monitor-config
  namespace: {{ .Values.team }}
  labels:
    app: {{ .Values.name }}
    project: vibranium
    monitoring: "true"
data:
  service: {{ .Values.name }}
  namespace: {{ .Values.team }}
  port: "{{ .Values.port }}"
